### ISSUE TITLE
Have you considered for this to become part of the stm32-rs organization?

### ISSUE THREAD

**Issue by matoushybl** [stm32-rs/bxcan#3]
Basically the title. I believe that if this is available only on STM32s and the HALs will become dependent on it, it might be a good idea to be maintained as part of the organization.

What do you think about it? This is just an idea I had when reviewing a PR that was adding the dependency, I certainly don't want to force you to move the repository there.

**Comment by jonas-schievink** [comment]
Yeah, I'm open to that, that sounds like a good idea.

**Comment by jonas-schievink** [comment]
The repo is now part of stm32-rs :tada:
